#spring:
# datasource:
#  hikari:#   jdbc-url: jdbc:sqlserver://hospitalserverdatabase.database.windows.net:1433
#   username: myadmin@hospitalserverdatabase
#   password: Shubham@1234
#   database-name: HospitalManagement
##   driver-class-name: oracle.jdbc.OracleDriver
##   connection-timeout: 20000 #maximum number of milliseconds that a client will wait for a connection
##   minimum-idle: 10 #minimum number of idle connections maintained by HikariCP in a connection pool
##   maximum-pool-size: 10 #maximum pool size
##   idle-timeout: 10000 #maximum idle time for connection
##   max-lifetime: 1000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
##   auto-commit: true #default auto-commit behavior.
#spring.jpa.database-platform: org.hibernate.dialect.Oracle12cDialect
##spring.jpa.hibernate.naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
server:  port: 8081
logging.level.org.springframework.web: DEBUG
#logging.level.org.hibernate: DEBUG
#logging.level.com.zaxxer.hikari.HikariConfig: DEBUG
#logging.level.org.hibernate.SQL: debug